---
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [-n 1, -lll, -q]
        exclude: >
          (?x)^(
              .*test.*.py
          )$
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.7.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
        args: [-l 144]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.4.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]

  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--line-length=144, --safe]
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: forbid-new-submodules
      - id: trailing-whitespace
